POST http://localhost:1012/movies/
Content-Type: application/json

{
  "title": "title",
  "description": "description",
  "trailer": "trailer",
  "year": 2007,
  "rating": 1,
  "genre_id": 3,
  "director_id": 4
}

###

GET http://localhost:1012/movies/
Accept: application/json

###

GET http://localhost:1012/movies/1
Accept: application/json

###

PUT http://localhost:1012/movies/1
Accept: application/json
Content-Type: application/json

{
  "title": "war of war",
  "description": "description",
  "trailer": "trailer",
  "year": 2007,
  "rating": 1,
  "genre_id": 3,
  "director_id": 4
}
###

DELETE http://localhost:1012/movies/1
Accept: application/json

###

PATCH http://localhost:1012/movies/1
Accept: application/json
Content-Type: application/json

{
  "title": "super"
}

###